version = 1

[envs.acme]
channels = ["conda-forge"]

[envs.acme.dependencies]
nodejs = "20.*"
python = "3.11.*"
go = "1.21.*"
rust = "*"
vim = "*"
nvim = "*"
tmux = "*"
eza = "*"
fzf = "*"
zoxide = "*"
yazi = "*"
ripgrep = "*"
bat = "*"
hugo = "*"
gh = "*"
git = "*"
htop = "*"
wget = "*"
curl = "*"

[envs.acme.exposed]
node = "node"
npm = "npm"
npx = "npx"
python = "python"
go = "go"
cargo = "cargo"
rustc = "rustc"
vim = "vim"
nvim = "nvim"
tmux = "tmux"
eza = "eza"
fzf = "fzf"
zoxide = "zoxide"
yazi = "yazi"
rg = "rg"
bat = "bat"
hugo = "hugo"
gh = "gh"
git = "git"
htop = "htop"
wget = "wget"
curl = "curl"
